# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from plotcanvas import PlotCanvas


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 60, 311, 411))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")

        self.widget = PlotCanvas(self.gridLayoutWidget)
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.Edge_Title_2 = QtWidgets.QLabel(self.centralwidget)
        self.Edge_Title_2.setGeometry(QtCore.QRect(410, 30, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Edge_Title_2.setFont(font)
        self.Edge_Title_2.setObjectName("Edge_Title_2")
        self.comboBoxFrom_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxFrom_2.setGeometry(QtCore.QRect(410, 90, 91, 31))
        self.comboBoxFrom_2.setObjectName("comboBoxFrom_2")
        self.comboBoxFrom_2.addItem("")
        self.comboBoxFrom_2.addItem("")
        self.comboBoxFrom_2.addItem("")
        self.comboBoxFrom_2.addItem("")
        self.comboBoxFrom_2.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(530, 100, 31, 16))
        self.label_2.setObjectName("label_2")
        self.pushButton_addEdge_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_addEdge_2.setGeometry(QtCore.QRect(700, 90, 61, 31))
        self.pushButton_addEdge_2.setObjectName("pushButton_addEdge_2")
        self.comboBoxFrom_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxFrom_3.setGeometry(QtCore.QRect(570, 90, 91, 31))
        self.comboBoxFrom_3.setObjectName("comboBoxFrom_3")
        self.comboBoxFrom_3.addItem("")
        self.comboBoxFrom_3.addItem("")
        self.comboBoxFrom_3.addItem("")
        self.comboBoxFrom_3.addItem("")
        self.comboBoxFrom_3.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.pushButton_addEdge_2.clicked.connect(self.pressed)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Edge_Title_2.setText(_translate("MainWindow", "Add An Edge"))
        self.comboBoxFrom_2.setItemText(0, _translate("MainWindow", "RI"))
        self.comboBoxFrom_2.setItemText(1, _translate("MainWindow", "JK"))
        self.comboBoxFrom_2.setItemText(2, _translate("MainWindow", "HU"))
        self.comboBoxFrom_2.setItemText(3, _translate("MainWindow", "SE"))
        self.comboBoxFrom_2.setItemText(4, _translate("MainWindow", "KH"))
        self.label_2.setText(_translate("MainWindow", "to"))
        self.pushButton_addEdge_2.setText(_translate("MainWindow", "Add"))
        self.comboBoxFrom_3.setItemText(0, _translate("MainWindow", "RI"))
        self.comboBoxFrom_3.setItemText(1, _translate("MainWindow", "JK"))
        self.comboBoxFrom_3.setItemText(2, _translate("MainWindow", "HU"))
        self.comboBoxFrom_3.setItemText(3, _translate("MainWindow", "SE"))
        self.comboBoxFrom_3.setItemText(4, _translate("MainWindow", "KH"))

    def pressed(self):
        self.gridLayout.itemAt(0).widget().deleteLater()
        node_from = self.comboBoxFrom_2.currentText()
        node_to = self.comboBoxFrom_3.currentText()
        self.widget.get_graph().add_edge(node_from, node_to, weight=100)
        self.widget = PlotCanvas(self.gridLayoutWidget)
        self.gridLayout.addWidget(self.widget, 0, 0)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
